### ISSUE TITLE
Dependency hierarchy has become too complex

### ISSUE THREAD

**Issue by djanloo** [djanloo/quilt#22]
This is the dependency list for compiling `oscill.pyx`:
``` yaml
oscill:
  sources:
    - interface/oscill.pyx
    - core/multiscale.cpp
    - core/oscillators.cpp
    - core/network.cpp
    - core/neurons_base.cpp
    - core/neuron_models.cpp
    - core/links.cpp
    - core/devices.cpp
    - core/base.cpp
  include_dirs:
    - core/include
```

Oscillators should not depend on the spiking code. Why is it like this?

**Comment by djanloo** [comment]
The ideal structure should be like

``` yaml
oscill:
  - base
  - (devices, but maybe useful for future cortical devices)
  - links
  - oscillators
spiking:
  - base
  - devices
  - neurons_base
  - neuron_models
  - network
multiscale:
  everything
```

```
